name: Build unmpkg binary for arm64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set env
        run: |
          echo build_time=$(TZ=Asia/Shanghai date '+%Y%m%d%H%M') | tee -a $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Install packages
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu22.04
          run: |
            apt update && apt install gcc -y
            gcc unmpkg.c -o unmpkg
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: unmpkg
          body: |
            This is unmpkg binary release.
            Build time: ${{ env.build_time }}
          prerelease: false
          files: |
            /home/runner/work/unmpkg/unmpkg/unmpkg
