name: Build unmpkg binary for arm64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set env
        run: |
          echo build_time=$(TZ=Asia/Shanghai date '+%Y%m%d%H%M') | tee -a $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: build
        run: |
            sudo apt update && sudo apt install g++-aarch64-linux-gnu
            aarch64-linux-gnu-gcc unmpkg.c -o unmpkg-arm64 --static
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: unmpkg
          body: |
            This is unmpkg static binary release.
            Build time: ${{ env.build_time }}
          prerelease: false
          files: |
            /home/runner/work/unmpkg/unmpkg/unmpkg-arm64
